### ISSUE TITLE
Full image or the cropped regions used in VG dataset?

### ISSUE THREAD

**Issue by flymark2010** [zerovl/ZeroVL#4]
Hi, thanks for your great work.

In your paper, you meaned that "we filter 5 out of 50 captions for each image according to largest areas of bounding box regions". In VG, the caption is for each bounding box region, so if you cropped the region to train or use the full image?

**Comment by zerovl** [comment]
thanks for your question.

We save cropped regions as individual image-text pairs for training. We do not use the full image, but you can try it.

According to our experience, VG is not the most important dataset and its usage does not significantly influence the model performance.

**Comment by zerovl** [comment]
BTW, do not use extremely small cropped regions, and it could hurt model performance.

**Comment by flymark2010** [comment]
Got it, thanks.
